CREATE TABLE REG_DATA (
  `ID`  SMALLINT AUTO_INCREMENT NOT NULL,
  `DATE` DATE not NULL,
  `REGION` VARCHAR(10),
  `KPI_1` FLOAT,
  `KPI_2` FLOAT,
  `KPI_3` FLOAT,
  `KPI_4` FLOAT,
  `KPI_5` FLOAT,
  `KPI_6` FLOAT,
  `KPI_7` FLOAT,
  PRIMARY KEY(ID)
);

CREATE TABLE OBL_LIST (
  `ID`  SMALLINT AUTO_INCREMENT NOT NULL,
  `REGION` VARCHAR(10),
  `OBL` VARCHAR(10),
  PRIMARY KEY(ID)
);

CREATE TABLE DIST_DATA (
  `ID`  SMALLINT AUTO_INCREMENT NOT NULL,
  `DATE` DATE not NULL,
  `DISTRICT` VARCHAR(10),
  `KPI_1` FLOAT,
  `KPI_2` FLOAT,
  `KPI_3` FLOAT,
  `KPI_4` FLOAT,
  `KPI_5` FLOAT,
  `KPI_6` FLOAT,
  PRIMARY KEY(ID)
);

CREATE TABLE EQUIP_DATA (
  `ID`  MEDIUMINT AUTO_INCREMENT NOT NULL,
  `DATE` DATE not NULL,
  `DISTRICT` VARCHAR(10),
  `EQUIPMENT` VARCHAR(10),
  `KPI_1` FLOAT,
  `KPI_2` FLOAT,
  `KPI_3` FLOAT,
  `KPI_4` FLOAT,
  `KPI_5` FLOAT,
  `KPI_6` FLOAT,
  PRIMARY KEY(ID)
);